/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#33343b",
        "accent-gold-bright": "#F5B955",
        "on-surface": "#e2e2eb",
        "primary": "#e8b072",
        "primary-hover": "#b45309",
        "on-error": "#690005",
        "glow-amber": "rgba(232, 176, 114, 0.18)",
        "error-container": "#93000a",
        "surface-container-high": "#282a30",
        "surface-container-lowest": "#0c0e14",
        "on-secondary-fixed": "#111c2d",
        "secondary-fixed": "#d8e3fb",
        "surface-dim": "#111319",
        "surface-container-low": "#191b22",
        "on-secondary-container": "#aeb9d0",
        "surface-container-highest": "#33343b",
        "tertiary": "#adddff",
        "border-active": "rgba(232, 176, 114, 0.45)",
        "on-secondary": "#263143",
        "tertiary-container": "#90c1e3",
        "error": "#ffb4ab",
        "primary-fixed": "#ffddbb",
        "on-primary-fixed-variant": "#653e09",
        "accent-gold-muted": "#C78D4D",
        "surface-glass": "rgba(24, 28, 40, 0.72)",
        "surface-elevated": "#131B2A",
        "surface-card": "#181C28",
        "on-tertiary-fixed-variant": "#124c69",
        "on-surface-variant": "#d4c4b5",
        "secondary-container": "#3e495d",
        "tertiary-fixed-dim": "#9bcdef",
        "on-primary-container": "#69420d",
        "surface-tint": "#f5bc7d",
        "inverse-on-surface": "#2e3037",
        "on-background": "#e2e2eb",
        "outline": "#9d8e81",
        "on-secondary-fixed-variant": "#3c475a",
        "on-tertiary-container": "#18506d",
        "primary-fixed-dim": "#f5bc7d",
        "surface-container": "#1e1f26",
        "surface-base": "#0B0D13",
        "on-primary": "#482900",
        "text-secondary": "#94A3B8",
        "text-primary": "#F8FAFC",
        "inverse-surface": "#e2e2eb",
        "background": "#111319",
        "secondary": "#bcc7de",
        "inverse-primary": "#805520",
        "primary-container": "#e8b072",
        "surface-bright": "#373940",
        "outline-variant": "#50453a",
        "on-error-container": "#ffdad6",
        "border-subtle": "rgba(232, 176, 114, 0.12)",
        "tertiary-fixed": "#c7e7ff",
        "on-primary-fixed": "#2b1700",
        "secondary-fixed-dim": "#bcc7de",
        "text-muted": "#64748B",
        "on-tertiary": "#00344c",
        "on-tertiary-fixed": "#001e2e",
        "surface": "#111319"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xl": "2rem",
        "space-3xl": "4rem",
        "space-sm": "0.75rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "space-md": "1rem",
        "margin-desktop": "2rem",
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem"
      },
      fontFamily: {
        "sans": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "display": ["Outfit", "system-ui", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-sm": ["Outfit", "system-ui", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "display-lg-mobile": ["Outfit", "system-ui", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-md": ["Outfit", "system-ui", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "system-ui", "sans-serif"],
        "display-lg": ["Outfit", "system-ui", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg": ["Outfit", "system-ui", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
